### ISSUE TITLE
Add GET '/repositories/search' to fetch tasks/features from repository

### ISSUE THREAD

**Issue by SaurabhAripra** [ariprainfotech/nnxt#19]
- As per current implementation when 'Estimator' adds any tasks in estimation, it is also added into repository
- So tasks can be added into estimation to add tasks into repository 
- Since both feature/tasks are stored into same model, this API should be used to search both task and features
- Create a repository-router that would house all the APIs related to repository
- Add method into repositoryModel and call that method from router

**Comment by asharmaaripratech** [comment]
Today, i am busy with the client's project so, i will not able to work on it full day, but i will try to give some time on it.

**Comment by SaurabhChouhan** [comment]
Done.
