### ISSUE TITLE
Estimation Filter

### ISSUE THREAD

**Issue by SaurabhChouhan** [ariprainfotech/nnxt#566]
By default we should set filters so that negotiator can see all the changes done by estimator in previous iteration and estimator can see all the changes done by negotiator in previous iteration. Once user clears filter or apply filter then it would be kept as is

**Comment by gauravaripraa** [comment]
sir it may take a while because on approve we need to clear all flags

**Comment by gauravaripraa** [comment]
-so for applying filter we have to check logged in user and check its role in this estimation
